Explicitly set C stadard to use
Since GCC 5.1 default mode for C is -std=gnu11.
Change back to -std=gnu89 to avoid build error:

[  244s] In file included from ../test/../nestegg/halloc/src/halloc.c:19:0:
[  244s] ../test/../nestegg/halloc/src/align.h:33:25: error: conflicting types for 'max_align_t'
[  244s]  typedef union max_align max_align_t;
[  244s] In file included from ../test/../nestegg/halloc/src/../halloc.h:18:0,
[  244s]                  from ../test/../nestegg/halloc/src/halloc.c:18:
[  244s] /usr/lib/gcc/i586-tizen-linux/5.1/include/stddef.h:429:3: note: previous declaration of 'max_align_t' was here
[  244s]  } max_align_t;

Change-Id: I625324fb5a23fed53bdcdbeaaea59d01a90e78d3
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>